# Generated by Django 2.1.7 on 2019-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergencycall',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('received', models.DateTimeField()),
                ('sent', models.DateTimeField()),
                ('priority', models.IntegerField(blank=True)),
                ('description', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('external_data', models.TextField()),
                ('place', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('unit', models.TextField(blank=True)),
                ('cross_street', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=25)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
