# Generated by Django 2.1.7 on 2019-04-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='external_data',
            field=models.TextField(blank=True),
        ),
    ]
