# Generated by Django 2.1.8 on 2019-04-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20190410_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycall',
            name='cad_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='messages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='responses',
            field=models.TextField(blank=True),
        ),
    ]
