# Generated by Django 2.1.8 on 2019-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_auto_20190417_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycall',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
