# Generated by Django 2.1.8 on 2019-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_emergencycall_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
