# Generated by Django 2.1.8 on 2019-04-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20190423_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='cad_code',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='lon',
            field=models.FloatField(),
        ),
    ]
